### ISSUE TITLE
Invalid license value

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/date-annotator-example#54]
```ValueError: Invalid value for `license` (Apache-2.0), must be one of ['afl-3.0', 'apache-2.0', 'artistic-2.0', 'bsl-1.0', 'bsd-2-clause', 'bsd-3-clause', 'bsd-3-clause-clear', 'cc', 'cc0-1.0', 'cc-by-4.0', 'cc-by-sa-4.0', 'wtfpl', 'ecl-2.0', 'epl-1.0', 'epl-2.0', 'eupl-1.1', 'agpl-3.0', 'gpl', 'gpl-2.0', 'gpl-3.0', 'lgpl', 'lgpl-2.1', 'lgpl-3.0', 'isc', 'lppl-1.3c', 'ms-pl', 'mit', 'mpl-2.0', 'osl-3.0', 'postgresql', 'ofl-1.1', 'ncsa', 'unlicense', 'zlib']```

Is the a possibility to have the schema avoid case validation? (Edit: I did some research and found that there isn't a way to specify case-insensitive enums: https://stackoverflow.com/questions/60772786/case-insensitive-string-parameter-in-schema-of-openapi)

**Comment by tschaffter** [comment]
Related to https://github.com/nlpsandbox/nlpsandbox-schemas/issues/62

**Comment by tschaffter** [comment]
The developer should comply with the spec that lists the possible values that the property `Service.license` can take. A (web) client can then translate this keyword to a more human-friendly string if needed (e.g. "Apache 2.0").
