### ISSUE TITLE
Review date regex

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/date-annotator-example#63]
- It seems that the separator `(-)` can be replaced by `-`
- Consider the example below where the last character is not taken into account because not including it is also valid according to the regex.

![image](https://user-images.githubusercontent.com/3056480/105768178-dbff7700-5f10-11eb-90e9-31ce15b3fd70.png)

See https://regexr.com/5l0op

**Comment by gkowalski** [comment]
Assigning this to me ?

**Comment by tschaffter** [comment]
Are you offering to help with this issue? Since you are the one who came up with these regex I thought that this task would be a good fit for you.
