### ISSUE TITLE
Documentation enhancement 

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/date-annotator-example#64]
The documentation in the README.md states 

Evaluate the performance of a local prediction file: 

  docker run --rm nlpsandbox/cli evaluate  

But does not explain the other options which are required , nor tell how to first get / produce these files 

 docker run --rm nlpsandbox/cli evaluate prediction --help

```
Usage: nlp-cli evaluate prediction [OPTIONS]

  Evaluate the performance of a local prediction file

Options:
  --pred_filepath PATH            Prediction filepath  [required]
  --gold_filepath PATH            Gold standard filepath  [required]
  --output PATH                   Specify output json path
  --eval_type [date|person|address]
                                  Type of evaluation.
  --help                          Show this message and exit.

(base) ➜  mcw-nlpsandbox-client git:(develop) ✗  
```

**Comment by tschaffter** [comment]
@gkowalski What README are you referring to? I don't see anything about `nlp-cli` in the README of this repo. Did you mean to open this ticket for the python client?

We don't have the client ready for doing local evaluation as we are still finalizing working on the input and output format of the evaluation script.

**Comment by gkowalski** [comment]
Incorrect project for this issue

**Comment by gkowalski** [comment]
done
